gText_Rowan_HelloThere::
	.string "Hello there!\n"
	.string "It's so very nice to meet you!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "$"

gText_Birch_Welcome::
	.string "My name is Rowan.\p"
	.string "However, everyone just calls me the\n"
	.string "Pokémon Professor.\p"
	.string "Before I go any further, is this your\n"
	.string "first adventure?\p"
	.string "If you need advice, I'm certainly\n"
	.string "capable of giving it.\p$"

gText_Rowan_ControlInfo::
	.string "The D-Pad moves the main character,\n"
	.string "and is also used to choose various\l"
	.string "headings and selections.\p"
	.string "The A Button is used to confirm a\n"
	.string "choice, check things, chat, and scroll\l"
	.string "text.\p"
	.string "The B Button is used to exit, cancel a\n"
	.string "choice, and cancel a mode.\p"
	.string "The Start Button opens the menu.\p"
	.string "The Select Button uses an item, such as\n"
	.string "a Bicycle, that has been registered in\l"
	.string "advance.\p"
	.string "Would you like to know more about\n"
	.string "anything else?\p$"

gText_Rowan_AdventureInfo::
	.string "You are about to enter a world where\n"
	.string "you will embark on a grand adventure\l"
	.string "of your very own.\p"
	.string "Speak to people and check things\n"
	.string "wherever you go, be it in towns, roads,\l"
	.string "or caves.\p"
	.string "Gather information and hints from\n"
	.string "every possible source.\p"
	.string "New paths will open to you when you help\n"
	.string "people in need, overcome challenges,\l"
	.string "and solve mysteries.\p"
	.string "At times, you will be challenged by\n"
	.string "others to a battle.\p"
	.string "At other times, wild creatures may\n"
	.string "stand in your way.\p"
	.string "By overcoming such hurdles, you will\n"
	.string "gain great power.\p"
	.string "However, your adventure is not solely\n"
	.string "about becoming powerful.\p"
	.string "On your travels, we hope that you will\n"
	.string "meet countless people and, through\l"
	.string "them, achieve personal growth.\p"
	.string "This is the most important objective of\n"
	.string "this adventure.\p"
	.string "Would you like to know more about\n"
	.string "anything else?\p$"

gText_Birch_MainSpeech::
	.string "We humans live alongside Pokémon as\n"
	.string "friends.\p"
	.string "At times we play together, and at other\n"
	.string "times we work together.\p"
	.string "Some people use their Pokémon to\n"
	.string "battle and develop closer bonds with\l"
	.string "them.\p"
	.string "What do I do?\p"
	.string "I conduct research so that we may learn\n"
	.string "more about Pokémon.\p$"

gText_Birch_AndYouAre::
	.string "Now, why don't you tell me a little bit\n"
	.string "about yourself?\p$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_YoureAGirl::
	.string "All right, so you're a girl?{PAUSE 10}$"

gText_Birch_YoureABoy::
	.string "All right, so you're a boy?{PAUSE 10}$"

gText_Birch_WhatsYourName::
	.string "Tell me, what is your name?$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}?{PAUSE 10}$"

gText_Birch_YourePlayer::
	.string "OK…\n"
	.string "So, you're {PLAYER}?\p"
	.string "A fine name that is!\p"
	.string "Now, this boy here…\n"
	.string "I believe he's your friend.\p$"

gText_Rowan_NameRival::
	.string "What might his name be?{PAUSE 10}$"

gText_Rowan_NameRival2::
	.string "{RIVAL}, is it?\n"
	.string "That's your friend's name?{PAUSE 10}$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}, the time has come.\p"
	.string "Your very own tale of grand adventure\n"
	.string "is about to unfold.\p"
	.string "On your journey, you will meet countless\n"
	.string "Pokémon and people.\p"
	.string "I'm sure that along the way you will\n"
	.string "discover many things, perhaps even\l"
	.string "something about yourself.\p"
	.string "Now, go on, leap into the world of\n"
	.string "Pokémon!\p$"
